import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { I } from "./icons";
import { STAGE_LABELS } from "../stages/data";
export function Sidebar({ stage, concept, onNewSession, onToggleCollapse }) {
    const [historyOpen, setHistoryOpen] = useState(true);
    const isActive = stage !== "input";
    return (_jsxs("aside", { className: "sidebar", children: [_jsxs("div", { className: "sb-brand", children: [_jsx("span", { className: "sb-brand-mark", children: I.brand }), _jsx("span", { className: "sb-brand-name", children: "Socratic" }), _jsx("button", { className: "sb-collapse", "aria-label": "\uC0AC\uC774\uB4DC\uBC14 \uC811\uAE30", onClick: onToggleCollapse, type: "button", children: I.sidebar })] }), _jsxs("button", { className: "sb-item is-primary" + (stage === "input" ? " is-active" : ""), type: "button", onClick: onNewSession, children: [_jsx("span", { className: "ico", children: I.capture }), "\uC0C8\uB85C \uD559\uC2B5\uD558\uAE30"] }), _jsxs("button", { className: "sb-item", type: "button", children: [_jsx("span", { className: "ico", children: I.archive }), "\uC544\uCE74\uC774\uBE0C"] }), _jsxs("button", { className: "sb-item", type: "button", children: [_jsx("span", { className: "ico", children: I.folder }), "\uD3F4\uB354"] }), _jsx("div", { className: "sb-divider" }), _jsxs("button", { className: "sb-section", "aria-expanded": historyOpen, onClick: () => setHistoryOpen((v) => !v), type: "button", children: [_jsx("span", { className: "ico", children: I.history }), "\uD559\uC2B5 \uD788\uC2A4\uD1A0\uB9AC", _jsx("span", { className: "chev", children: I.chevSmall })] }), historyOpen &&
                (isActive ? (_jsx("div", { className: "sb-history-list", children: _jsxs("button", { className: "sb-history-item is-active", type: "button", children: [_jsx("span", { className: "ti", children: concept }), _jsxs("span", { className: "mt", children: ["\uC9C4\uD589 \uC911 \u00B7 ", STAGE_LABELS[stage]] })] }) })) : (_jsx("div", { className: "sb-history-list", children: _jsx("div", { className: "sb-empty", children: "\uD788\uC2A4\uD1A0\uB9AC\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4" }) }))), _jsx("div", { className: "sb-spacer" }), _jsxs("div", { className: "sb-foot", children: [_jsxs("div", { className: "sb-user", children: [_jsx("div", { className: "sb-avatar", children: "\uC720" }), _jsxs("div", { style: { minWidth: 0 }, children: [_jsx("div", { className: "sb-user-name", children: "\uC720\uC544\uC774\uBCFC" }), _jsx("div", { className: "sb-user-meta", children: "Free plan" })] })] }), _jsxs("div", { className: "sb-quota", children: [_jsxs("span", { className: "pill", children: [I.figma, " 10\uAC74"] }), _jsxs("span", { className: "pill", children: [I.image, " 50\uAC74"] })] }), _jsx("button", { className: "sb-upgrade", type: "button", children: "\uD50C\uB79C \uC5C5\uADF8\uB808\uC774\uB4DC \u2192" })] })] }));
}
